### PR TITLE
Added new fandangle spacing mixin

### PR DESCRIPTION
**Pull request by chrisbuttery**
Have you been to India?

WELL GET THIS INDIA!

### CODE REVIEW

**Comment by anthonyshort** [comment]
You'll want to add this to the `https://github.com/anthonyshort/stitch-css/blob/master/stylesheets/stitch/patterns/_layout.scss` file as well so it gets included by default.

**Comment by chrisbuttery** [comment]
:metal:

**Comment by anthonyshort** [comment]
Rename them to `margin-` and `padding-` 

:squirrel:

**Comment by chrisbuttery** [comment]
No you do it 

:trollface:

**Pull request merged**
